server:
  port: 19091

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5441}/userdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000

logging:
  level:
    com.spatra.gt5lt7: INFO
  file:
    name: logs/user-service.log
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

  tracing:
    sampling:
      probability: 1.0