rootProject.name = 'logibox'

//include ':infrastructure:eureka-server'
//include ':infrastructure:api-gateway'

include ':module'
//include ':services:user-service'
//include ':services:hub-service'
include ':services:company-service'
//include ':services:product-service'
//include ':services:order-service'
//include ':services:delivery-service'
//include ':services:slack-ai-service'