spring:
  application:
    name: catalog-service

feign:
  client:
    config:
      kakao-map-client:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic  # 운영 환경에서 API Key가 로그에 찍히는 보안 취약점 방어

kakao:
  map:
    auth-header: "KakaoAK ${KAKAO_MAP_API_KEY}"