spring.application.name=logistics-service
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.autoconfigure.exclude=org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration