server:
  port: 19092

spring:
  application:
    name: logistics-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5442}/logisticsdb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

kakao:
  local:
    base-url: https://dapi.kakao.com
    api-key: ${KAKAO_API_KEY}
  mobility:
    base-url: https://apis-navi.kakaomobility.com
