spring.application.name=logistics-service
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kakao Local API
kakao.local.base-url=https://dapi.kakao.com
kakao.local.api-key=${KAKAO_MAP_API_KEY}

# Kakao Mobility API (Directions)
kakao.mobility.base-url=https://apis-navi.kakaomobility.com